project_id = "cechkvznlmzelmhpftcl"

[storage]
enabled = true

[[storage.buckets]]
name = "order-files"
public = true
file_size_limit = 10485760
allowed_mime_types = ["image/png", "image/jpeg", "image/jpg", "image/webp"]

[functions.create-admin]
verify_jwt = false
